name: Run FastAPI App

on:
  push:
    branches: [ dep/project ]
  pull_request:
    branches: [ dep/project ]

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
      AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT}}
      APP_NAME: ${{secrets.APP_NAME}}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --all-groups
        working-directory: backend

      - name: Validate FastAPI app
        run: uv run python -c "from app.main import app; print('App loaded successfully')"
        working-directory: backend
